import { clubSquad } from './clubDraftData';

export const basketballClubPlayers = [
  ...clubSquad('Boston Celtics','2020s',[['Jayson Tatum','Small Forward'],['Jaylen Brown','Shooting Guard'],['Jrue Holiday','Point Guard'],['Derrick White','Shooting Guard'],['Kristaps Porziņģis','Center'],['Al Horford','Center'],['Payton Pritchard','Point Guard'],['Sam Hauser','Small Forward']]),
  ...clubSquad('Los Angeles Lakers','2020s',[['LeBron James','Small Forward'],['Anthony Davis','Power Forward'],['Rajon Rondo','Point Guard'],['Kentavious Caldwell-Pope','Shooting Guard'],['Danny Green','Small Forward'],['Kyle Kuzma','Power Forward'],['Alex Caruso','Point Guard'],['Dwight Howard','Center']]),
  ...clubSquad('Golden State Warriors','2020s',[['Stephen Curry','Point Guard'],['Klay Thompson','Shooting Guard'],['Draymond Green','Power Forward'],['Andrew Wiggins','Small Forward'],['Kevon Looney','Center'],['Jordan Poole','Shooting Guard'],['Jonathan Kuminga','Power Forward'],['Moses Moody','Shooting Guard']]),
  ...clubSquad('Chicago Bulls','1990s',[['Michael Jordan','Shooting Guard'],['Scottie Pippen','Small Forward'],['Dennis Rodman','Power Forward'],['Toni Kukoč','Power Forward'],['Ron Harper','Point Guard'],['Luc Longley','Center'],['Steve Kerr','Shooting Guard'],['Horace Grant','Power Forward']]),
  ...clubSquad('San Antonio Spurs','2000s',[['Tim Duncan','Power Forward'],['Tony Parker','Point Guard'],['Manu Ginóbili','Shooting Guard'],['Bruce Bowen','Small Forward'],['David Robinson','Center'],['Robert Horry','Power Forward'],['Michael Finley','Small Forward'],['Brent Barry','Shooting Guard']]),
  ...clubSquad('Philadelphia 76ers','2020s',[['Joel Embiid','Center'],['Tyrese Maxey','Point Guard'],['James Harden','Shooting Guard'],['Tobias Harris','Power Forward'],['Ben Simmons','Point Guard'],['Jimmy Butler','Small Forward'],['JJ Redick','Shooting Guard'],['Al Horford','Center']]),
  ...clubSquad('Detroit Pistons','2000s',[['Chauncey Billups','Point Guard'],['Richard Hamilton','Shooting Guard'],['Tayshaun Prince','Small Forward'],['Rasheed Wallace','Power Forward'],['Ben Wallace','Center'],['Lindsey Hunter','Point Guard'],['Antonio McDyess','Power Forward'],['Mehmet Okur','Center']]),
  ...clubSquad('Miami Heat','2010s',[['LeBron James','Small Forward'],['Dwyane Wade','Shooting Guard'],['Chris Bosh','Power Forward'],['Mario Chalmers','Point Guard'],['Shane Battier','Small Forward'],['Ray Allen','Shooting Guard'],['Udonis Haslem','Power Forward'],['Chris Andersen','Center']]),
  ...clubSquad('New York Knicks','1990s',[['Patrick Ewing','Center'],['John Starks','Shooting Guard'],['Charles Oakley','Power Forward'],['Allan Houston','Shooting Guard'],['Anthony Mason','Small Forward'],['Derek Harper','Point Guard'],['Marcus Camby','Center'],['Latrell Sprewell','Small Forward']]),
  ...clubSquad('Houston Rockets','1990s',[['Hakeem Olajuwon','Center'],['Clyde Drexler','Shooting Guard'],['Charles Barkley','Power Forward'],['Kenny Smith','Point Guard'],['Vernon Maxwell','Shooting Guard'],['Robert Horry','Power Forward'],['Sam Cassell','Point Guard'],['Mario Elie','Small Forward']]),
];
