import type { Player, RankedItem } from './sportsData';

type Row = [string, string, string, string, string, string];
const players = (rows: Row[]): Player[] => rows.map(([name, detail, stat, badge, team, years]) => ({ name, detail, stat, badge, team, years, status: 'active', honours: [stat] }));

export const currentPlayers: Record<string, Player[]> = {
  football: players([
    ['Kylian Mbappé','Forward · France','Recent elite scoring and major-title impact','KM','Real Madrid','2015–present'],['Lamine Yamal','Winger · Spain','Recent league-winning and international impact','LY','Barcelona','2023–present'],['Lionel Messi','Forward · Argentina','Recent league MVP-level form and international impact','LM','Inter Miami','2004–present'],['Ousmane Dembélé','Winger · France','Recent title-winning MVP-level form','OD','Paris Saint-Germain','2012–present'],['Erling Haaland','Forward · Norway','Multiple recent Golden Boots','EH','Manchester City','2015–present'],['Jude Bellingham','Midfielder · England','Recent league and Champions League impact','JB','Real Madrid','2020–present'],['Vinícius Júnior','Winger · Brazil','Recent Champions League match-winning impact','VJ','Real Madrid','2017–present'],['Mohamed Salah','Winger · Egypt','Recent league title and scoring impact','MS','Liverpool','2010–present'],['Harry Kane','Forward · England','Recent European Golden Shoe and league title','HK','Bayern Munich','2009–present'],['Rodri','Midfielder · Spain','Ballon d’Or and recent title impact','ROD','Manchester City','2015–present'],
  ]),
  basketball: players([
    ['Nikola Jokić','Center · Serbia','Multiple NBA MVP awards','NJ','Denver Nuggets','2015–present'],['Shai Gilgeous-Alexander','Point Guard · Canada','NBA MVP and championship impact','SGA','Oklahoma City Thunder','2018–present'],['Luka Dončić','Point Guard · Slovenia','Multiple All-NBA First Team selections','LD','Los Angeles Lakers','2018–present'],['Giannis Antetokounmpo','Power Forward · Greece','Two MVP awards and NBA championship','GA','Milwaukee Bucks','2013–present'],['Jayson Tatum','Small Forward · USA','NBA championship and All-NBA honours','JT','Boston Celtics','2017–present'],['Victor Wembanyama','Center · France','Recent Defensive Player of the Year-level impact','VW','San Antonio Spurs','2023–present'],['Stephen Curry','Point Guard · USA','Recent All-NBA and scoring impact','SC','Golden State Warriors','2009–present'],['Anthony Edwards','Shooting Guard · USA','Recent All-NBA playoff impact','AE','Minnesota Timberwolves','2020–present'],['Jalen Brunson','Point Guard · USA','Recent All-NBA playoff impact','JB','New York Knicks','2018–present'],['LeBron James','Small Forward · USA','Recent All-NBA impact and scoring record','LJ','Los Angeles Lakers','2003–present'],
  ]),
  tennis: players([
    ['Jannik Sinner','All-court · Italy','Current world-leading Grand Slam form','JS','Italy','2018–present'],['Alexander Zverev','Baseliner · Germany','Recent Wimbledon finalist and top ranking','AZ','Germany','2013–present'],['Carlos Alcaraz','All-court · Spain','Multiple recent Grand Slam titles','CA','Spain','2018–present'],['Novak Djokovic','All-court · Serbia','24 major singles titles','ND','Serbia','2003–present'],['Ben Shelton','Aggressive baseliner · USA','Recent top-ten and Masters-level form','BS','United States','2022–present'],['Taylor Fritz','Baseliner · USA','Recent Grand Slam finalist and top-ten form','TF','United States','2015–present'],['Jack Draper','Left-handed · Great Britain','Recent Masters title and top-ten form','JD','Great Britain','2018–present'],['Lorenzo Musetti','All-court · Italy','Recent major semifinal and top-ten form','LM','Italy','2019–present'],['Holger Rune','Baseliner · Denmark','Masters champion and top-ten form','HR','Denmark','2020–present'],['Alex de Minaur','Counterpuncher · Australia','Recent top-ten consistency','ADM','Australia','2015–present'],
  ]),
  f1: players([
    ['Kimi Antonelli','Driver · Italy','2026 championship-leading race winner','KA','Mercedes','2025–present'],['George Russell','Driver · Great Britain','Multiple 2026 race wins','GR','Mercedes','2019–present'],['Lewis Hamilton','Driver · Great Britain','2026 race winner and seven world titles','LH','Ferrari','2007–present'],['Charles Leclerc','Driver · Monaco','2026 race winner','CL','Ferrari','2018–present'],['Max Verstappen','Driver · Netherlands','Multiple world championships','MV','Red Bull Racing','2015–present'],['Lando Norris','Driver · Great Britain','World champion and 2026 podium form','LN','McLaren','2019–present'],['Oscar Piastri','Driver · Australia','Recent race-winning form','OP','McLaren','2023–present'],['Pierre Gasly','Driver · France','Recent 2026 podium form','PG','Alpine','2017–present'],['Oliver Bearman','Driver · Great Britain','Recent points-scoring form','OB','Haas','2024–present'],['Fernando Alonso','Driver · Spain','Two world titles and active podium contender','FA','Aston Martin','2001–present'],
  ]),
  baseball: players([
    ['Aaron Judge','Outfielder · USA','Recent MVP and home-run leadership','AJ','New York Yankees','2016–present'],['Shohei Ohtani','Two-way player · Japan','Multiple MVP awards and World Series title','SO','Los Angeles Dodgers','2018–present'],['Bobby Witt Jr.','Shortstop · USA','Recent batting-title and MVP-level form','BWJ','Kansas City Royals','2022–present'],['Juan Soto','Outfielder · Dominican Republic','Recent elite on-base and playoff impact','JS','New York Mets','2018–present'],['Tarik Skubal','Pitcher · USA','Recent Cy Young-winning form','TS','Detroit Tigers','2019–present'],['Paul Skenes','Pitcher · USA','Recent Rookie of the Year and Cy Young-level form','PS','Pittsburgh Pirates','2024–present'],['Cal Raleigh','Catcher · USA','Recent home-run and MVP-level form','CR','Seattle Mariners','2019–present'],['José Ramírez','Third base · Dominican Republic','Recent All-MLB and MVP-level form','JR','Cleveland Guardians','2013–present'],['Vladimir Guerrero Jr.','First base · Canada','Recent postseason and Silver Slugger impact','VGJ','Toronto Blue Jays','2019–present'],['Kyle Tucker','Outfielder · USA','Recent All-Star and Silver Slugger form','KT','Chicago Cubs','2018–present'],
  ]),
  'american-football': players([
    ['Josh Allen','Quarterback · USA','Recent NFL MVP','JA','Buffalo Bills','2018–present'],['Patrick Mahomes','Quarterback · USA','Multiple MVP and Super Bowl wins','PM','Kansas City Chiefs','2017–present'],['Lamar Jackson','Quarterback · USA','Multiple NFL MVP awards','LJ','Baltimore Ravens','2018–present'],['Joe Burrow','Quarterback · USA','Recent passing-title form','JB','Cincinnati Bengals','2020–present'],['Saquon Barkley','Running back · USA','Recent championship and rushing-title impact','SB','Philadelphia Eagles','2018–present'],['Jalen Hurts','Quarterback · USA','Recent Super Bowl-winning impact','JH','Philadelphia Eagles','2020–present'],['Justin Jefferson','Wide receiver · USA','Offensive Player of the Year-level form','JJ','Minnesota Vikings','2020–present'],['Ja’Marr Chase','Wide receiver · USA','Recent receiving triple-crown form','JC','Cincinnati Bengals','2021–present'],['Myles Garrett','Defensive end · USA','Defensive Player of the Year-level form','MG','Cleveland Browns','2017–present'],['Micah Parsons','Linebacker · USA','Recent All-Pro defensive impact','MP','Dallas Cowboys','2021–present'],
  ]),
  ufc: players([
    ['Ilia Topuria','Champion · Spain/Georgia','Recent two-division championship impact','IT','Climent Club','2015–present'],['Islam Makhachev','Champion · Russia','Long UFC winning streak and title defenses','IM','AKA','2010–present'],['Khamzat Chimaev','Middleweight · UAE','Recent unbeaten championship form','KC','Allstars Training Center','2018–present'],['Alex Pereira','Light heavyweight · Brazil','Multiple recent UFC title wins','AP','Teixeira MMA','2015–present'],['Tom Aspinall','Heavyweight · England','UFC heavyweight championship','TA','Team Kaobon','2014–present'],['Merab Dvalishvili','Bantamweight · Georgia','Recent title defenses and winning streak','MD','Serra-Longo','2014–present'],['Alexandre Pantoja','Flyweight · Brazil','Recent UFC title defenses','APJ','American Top Team','2007–present'],['Max Holloway','Featherweight · USA','Recent BMF and title-contender impact','MH','Gracie Technics','2010–present'],['Alexander Volkanovski','Featherweight · Australia','Multiple UFC title defenses','AV','Freestyle MMA','2012–present'],['Valentina Shevchenko','Flyweight · Kyrgyzstan','Multiple UFC title defenses','VS','Tiger Muay Thai','2003–present'],
  ]),
  swimming: players([
    ['Léon Marchand','Medley · France','Multiple Olympic gold medals','LM','France','2019–present'],['Summer McIntosh','Medley/Freestyle · Canada','Multiple Olympic and world titles','SM','Canada','2021–present'],['Katie Ledecky','Distance freestyle · USA','Multiple Olympic and world titles','KL','United States','2012–present'],['Mollie O’Callaghan','Freestyle · Australia','Multiple Olympic and world titles','MO','Australia','2019–present'],['Pan Zhanle','Sprint freestyle · China','Olympic champion and world record','PZ','China','2021–present'],['David Popovici','Freestyle · Romania','Olympic and world champion','DP','Romania','2020–present'],['Thomas Ceccon','Backstroke · Italy','Olympic and world champion','TC','Italy','2017–present'],['Regan Smith','Backstroke · USA','Olympic champion and world records','RS','United States','2017–present'],['Torri Huske','Butterfly/Freestyle · USA','Multiple Olympic gold medals','TH','United States','2019–present'],['Kate Douglass','Medley/Breaststroke · USA','Olympic and world champion','KD','United States','2016–present'],
  ]),
  volleyball: players([
    ['Wilfredo León','Outside hitter · Poland','Recent Olympic and club-title impact','WL','Poland','2008–present'],['Earvin N’Gapeth','Outside hitter · France','Multiple Olympic gold medals','EN','France','2008–present'],['Tijana Bošković','Opposite · Serbia','Multiple world titles and MVP awards','TB','Serbia','2013–present'],['Zhu Ting','Outside hitter · China','Olympic and world champion','ZT','China','2011–present'],['Alessandro Michieletto','Outside hitter · Italy','Recent world-title and club impact','AM','Italy','2020–present'],['Paola Egonu','Opposite · Italy','Recent Olympic and MVP impact','PE','Italy','2015–present'],['Gabi Guimarães','Outside hitter · Brazil','Recent Olympic and club-title impact','GG','Brazil','2012–present'],['Antoine Brizard','Setter · France','Multiple Olympic gold medals','AB','France','2012–present'],['Yuji Nishida','Opposite · Japan','Recent international scoring impact','YN','Japan','2018–present'],['Simone Giannelli','Setter · Italy','World champion and MVP awards','SG','Italy','2012–present'],
  ]),
  'track-sprint': players([
    ['Noah Lyles','100m/200m · USA','Olympic and world champion','NL','United States','2016–present'],['Letsile Tebogo','100m/200m · Botswana','Olympic 200m champion','LT','Botswana','2021–present'],['Julien Alfred','100m/200m · Saint Lucia','Olympic 100m champion','JA','Saint Lucia','2017–present'],['Sydney McLaughlin-Levrone','400m · USA','Olympic champion and world record holder','SML','United States','2014–present'],['Marileidy Paulino','400m · Dominican Republic','Olympic champion','MP','Dominican Republic','2015–present'],['Sha’Carri Richardson','100m/200m · USA','World champion and Olympic medalist','SCR','United States','2019–present'],['Melissa Jefferson-Wooden','100m · USA','Recent world-leading sprint form','MJW','United States','2018–present'],['Kishane Thompson','100m · Jamaica','Olympic medalist and elite sprint form','KT','Jamaica','2021–present'],['Oblique Seville','100m · Jamaica','Recent world-leading sprint form','OS','Jamaica','2017–present'],['Quincy Hall','400m · USA','Olympic 400m champion','QH','United States','2019–present'],
  ]),
};

export const recentTeamOrder: Record<string, string[]> = {
  football:['Paris Saint-Germain','Barcelona','Liverpool','Bayern Munich','Inter Milan','Arsenal','Manchester City','Real Madrid','Atlético Madrid','Bayer Leverkusen'], basketball:['Oklahoma City Thunder','Boston Celtics','New York Knicks','Indiana Pacers','Denver Nuggets','Minnesota Timberwolves','Cleveland Cavaliers','Los Angeles Lakers','Golden State Warriors','San Antonio Spurs'], tennis:['Italy','Spain','Germany','United States','Australia','Serbia','Great Britain','France','Sweden','Czech Republic (women)'], f1:['Mercedes','Ferrari','McLaren','Red Bull Racing','Williams','Aston Martin','Renault','Haas','Lotus','Benetton'], baseball:['Los Angeles Dodgers','New York Yankees','Detroit Tigers','Chicago Cubs','New York Mets','Seattle Mariners','Cleveland Guardians','Toronto Blue Jays','Philadelphia Phillies','San Diego Padres'], 'american-football':['Philadelphia Eagles','Buffalo Bills','Kansas City Chiefs','Baltimore Ravens','Detroit Lions','Los Angeles Rams','Minnesota Vikings','Green Bay Packers','Denver Broncos','Washington Commanders'], ufc:['City Kickboxing','American Top Team','AKA','Tiger Muay Thai','Xtreme Couture','Kill Cliff FC','Kings MMA','Team Alpha Male','Nova União','Renegade MMA'], swimming:['United States','Australia','France','Canada','China','Italy','Great Britain','Romania','Japan','Hungary'], volleyball:['France','Italy','Poland','Brazil','Japan','United States','Türkiye','Serbia','Slovenia','China'], 'track-sprint':['United States','Jamaica','Botswana','Saint Lucia','Dominican Republic','South Africa','Canada','Great Britain','Bahamas','Nigeria'], fortnite:['Team Falcons','Dignitas','Gentle Mates','Karmine Corp','Twisted Minds','XSET','Team Liquid','NRG','FaZe Clan','100 Thieves'], 'counter-strike-2':['Team Spirit','Team Vitality','Natus Vincere','MOUZ','G2 Esports','FaZe Clan','FURIA','Team Liquid','Astralis','Ninjas in Pyjamas'],
};

export function orderCurrentTeams(teams: RankedItem[], sportId: string) {
  const order = recentTeamOrder[sportId] ?? [];
  if (!order.length) return teams.slice(0, 10);
  return order.slice(0, 10).map((name, index) => teams.find((team) => team.name === name) ?? {
    name, detail: 'Current Edition · Recent performance', stat: `Recent-form rank #${index + 1}`,
    badge: name.split(' ').map((word) => word[0]).join('').slice(0, 3).toUpperCase(), honours: ['Current Edition recent-form ranking'],
  });
}
